# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import neonat_pb2 as neonat__pb2


class NeoNatStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.InserirPacientes = channel.unary_unary(
        '/NeoNat/InserirPacientes',
        request_serializer=neonat__pb2.RegistrarPacientes.SerializeToString,
        response_deserializer=neonat__pb2.RegistrarPacientesResposta.FromString,
        )
    self.EditarPacientes = channel.unary_unary(
        '/NeoNat/EditarPacientes',
        request_serializer=neonat__pb2.AtualizarPacientes.SerializeToString,
        response_deserializer=neonat__pb2.AtualizarPacientesResposta.FromString,
        )
    self.ExcluirPacientes = channel.unary_unary(
        '/NeoNat/ExcluirPacientes',
        request_serializer=neonat__pb2.DeletarPacientes.SerializeToString,
        response_deserializer=neonat__pb2.DeletarPacientesResposta.FromString,
        )
    self.PesquisarPacientes = channel.unary_unary(
        '/NeoNat/PesquisarPacientes',
        request_serializer=neonat__pb2.ConsultarPacientes.SerializeToString,
        response_deserializer=neonat__pb2.ConsultarPacientesResposta.FromString,
        )
    self.ListarPacientes = channel.unary_unary(
        '/NeoNat/ListarPacientes',
        request_serializer=neonat__pb2.TodosPacientes.SerializeToString,
        response_deserializer=neonat__pb2.TodosPacientesResposta.FromString,
        )
    self.InserirProcedimentos = channel.unary_unary(
        '/NeoNat/InserirProcedimentos',
        request_serializer=neonat__pb2.RegistrarProcedimentos.SerializeToString,
        response_deserializer=neonat__pb2.RegistrarProcedimentosResposta.FromString,
        )
    self.EditarProcedimentos = channel.unary_unary(
        '/NeoNat/EditarProcedimentos',
        request_serializer=neonat__pb2.AtualizarProcedimentos.SerializeToString,
        response_deserializer=neonat__pb2.AtualizarProcedimentosResposta.FromString,
        )
    self.ExcluirProcedimentos = channel.unary_unary(
        '/NeoNat/ExcluirProcedimentos',
        request_serializer=neonat__pb2.DeletarProcedimentos.SerializeToString,
        response_deserializer=neonat__pb2.DeletarProcedimentosResposta.FromString,
        )
    self.PesquisarProcedimentos = channel.unary_unary(
        '/NeoNat/PesquisarProcedimentos',
        request_serializer=neonat__pb2.ConsultarProcedimentos.SerializeToString,
        response_deserializer=neonat__pb2.ConsultarProcedimentosResposta.FromString,
        )
    self.ListarProcedimentos = channel.unary_unary(
        '/NeoNat/ListarProcedimentos',
        request_serializer=neonat__pb2.TodosProcedimentosPaciente.SerializeToString,
        response_deserializer=neonat__pb2.TodosProcedimentosPacienteResposta.FromString,
        )
    self.InserirMedico = channel.unary_unary(
        '/NeoNat/InserirMedico',
        request_serializer=neonat__pb2.RegistrarMedico.SerializeToString,
        response_deserializer=neonat__pb2.RegistrarMedicoResposta.FromString,
        )
    self.ListarMedicos = channel.unary_unary(
        '/NeoNat/ListarMedicos',
        request_serializer=neonat__pb2.TodosMedicos.SerializeToString,
        response_deserializer=neonat__pb2.TodosMedicosResposta.FromString,
        )
    self.PesquisarPacientesMedico = channel.unary_unary(
        '/NeoNat/PesquisarPacientesMedico',
        request_serializer=neonat__pb2.TodosPacientesMedico.SerializeToString,
        response_deserializer=neonat__pb2.TodosPacientesMedicoResposta.FromString,
        )


class NeoNatServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def InserirPacientes(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EditarPacientes(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ExcluirPacientes(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PesquisarPacientes(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListarPacientes(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def InserirProcedimentos(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EditarProcedimentos(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ExcluirProcedimentos(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PesquisarProcedimentos(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListarProcedimentos(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def InserirMedico(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListarMedicos(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PesquisarPacientesMedico(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_NeoNatServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'InserirPacientes': grpc.unary_unary_rpc_method_handler(
          servicer.InserirPacientes,
          request_deserializer=neonat__pb2.RegistrarPacientes.FromString,
          response_serializer=neonat__pb2.RegistrarPacientesResposta.SerializeToString,
      ),
      'EditarPacientes': grpc.unary_unary_rpc_method_handler(
          servicer.EditarPacientes,
          request_deserializer=neonat__pb2.AtualizarPacientes.FromString,
          response_serializer=neonat__pb2.AtualizarPacientesResposta.SerializeToString,
      ),
      'ExcluirPacientes': grpc.unary_unary_rpc_method_handler(
          servicer.ExcluirPacientes,
          request_deserializer=neonat__pb2.DeletarPacientes.FromString,
          response_serializer=neonat__pb2.DeletarPacientesResposta.SerializeToString,
      ),
      'PesquisarPacientes': grpc.unary_unary_rpc_method_handler(
          servicer.PesquisarPacientes,
          request_deserializer=neonat__pb2.ConsultarPacientes.FromString,
          response_serializer=neonat__pb2.ConsultarPacientesResposta.SerializeToString,
      ),
      'ListarPacientes': grpc.unary_unary_rpc_method_handler(
          servicer.ListarPacientes,
          request_deserializer=neonat__pb2.TodosPacientes.FromString,
          response_serializer=neonat__pb2.TodosPacientesResposta.SerializeToString,
      ),
      'InserirProcedimentos': grpc.unary_unary_rpc_method_handler(
          servicer.InserirProcedimentos,
          request_deserializer=neonat__pb2.RegistrarProcedimentos.FromString,
          response_serializer=neonat__pb2.RegistrarProcedimentosResposta.SerializeToString,
      ),
      'EditarProcedimentos': grpc.unary_unary_rpc_method_handler(
          servicer.EditarProcedimentos,
          request_deserializer=neonat__pb2.AtualizarProcedimentos.FromString,
          response_serializer=neonat__pb2.AtualizarProcedimentosResposta.SerializeToString,
      ),
      'ExcluirProcedimentos': grpc.unary_unary_rpc_method_handler(
          servicer.ExcluirProcedimentos,
          request_deserializer=neonat__pb2.DeletarProcedimentos.FromString,
          response_serializer=neonat__pb2.DeletarProcedimentosResposta.SerializeToString,
      ),
      'PesquisarProcedimentos': grpc.unary_unary_rpc_method_handler(
          servicer.PesquisarProcedimentos,
          request_deserializer=neonat__pb2.ConsultarProcedimentos.FromString,
          response_serializer=neonat__pb2.ConsultarProcedimentosResposta.SerializeToString,
      ),
      'ListarProcedimentos': grpc.unary_unary_rpc_method_handler(
          servicer.ListarProcedimentos,
          request_deserializer=neonat__pb2.TodosProcedimentosPaciente.FromString,
          response_serializer=neonat__pb2.TodosProcedimentosPacienteResposta.SerializeToString,
      ),
      'InserirMedico': grpc.unary_unary_rpc_method_handler(
          servicer.InserirMedico,
          request_deserializer=neonat__pb2.RegistrarMedico.FromString,
          response_serializer=neonat__pb2.RegistrarMedicoResposta.SerializeToString,
      ),
      'ListarMedicos': grpc.unary_unary_rpc_method_handler(
          servicer.ListarMedicos,
          request_deserializer=neonat__pb2.TodosMedicos.FromString,
          response_serializer=neonat__pb2.TodosMedicosResposta.SerializeToString,
      ),
      'PesquisarPacientesMedico': grpc.unary_unary_rpc_method_handler(
          servicer.PesquisarPacientesMedico,
          request_deserializer=neonat__pb2.TodosPacientesMedico.FromString,
          response_serializer=neonat__pb2.TodosPacientesMedicoResposta.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'NeoNat', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
